In [2]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [6]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [7]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [8]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [10]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
종속1 = 아이리스[['품종']]
print(독립.shape, 종속.shape, 종속1.shape)

(150, 4) (150, 3) (150, 1)


In [ ]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1263 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1261 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1267 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1263 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1262 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1259 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1261 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1257 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1263 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1258 - accuracy: 0.9800


In [ ]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9968970e-01 3.1028493e-04 1.5116044e-09]
 [9.9815089e-01 1.8490498e-03 2.3181773e-08]
 [9.9934810e-01 6.5187435e-04 7.1573996e-09]
 [9.9807125e-01 1.9287227e-03 4.6842064e-08]
 [9.9977940e-01 2.2056155e-04 1.1390902e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 학습한 가중치
model.get_weights()

[array([[ 1.1206117 ,  1.0070976 , -0.76022446],
        [ 3.6882255 ,  0.16067708, -1.0229104 ],
        [-4.57068   , -0.96101767,  1.532893  ],
        [-4.1812778 , -1.1235818 ,  2.1811411 ]], dtype=float32),
 array([ 2.22937  ,  1.4119343, -1.8166612], dtype=float32)]