# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [ ]:
#1. 과거의 데이터를 준비합니다.
파일경로 = '/content/boston.csv'
보스턴 = pd.read_csv(파일경로)

#종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.9763
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 26.1203
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.9813
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 24.7751
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 25.1300
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 24.4888
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 25.1748
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 24.1443
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 25.6121
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3392


In [ ]:
# 4. 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[29.875679]
 [24.5941  ]
 [31.143375]
 [29.89589 ]
 [29.418259]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류


In [3]:
#1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)

#종속변수, 독립변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [4]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [7]:
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

In [ ]:
# 4. 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[1.0000000e+00 5.6188866e-11 5.0029675e-15]
 [1.0000000e+00 1.4186266e-08 9.0516131e-13]
 [1.0000000e+00 8.4865925e-10 7.9909718e-14]
 [1.0000000e+00 2.7057682e-08 8.9389092e-13]
 [1.0000000e+00 2.6075730e-11 2.2111196e-15]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
